FROM node:18-alpine

WORKDIR /app

# 使用阿里云镜像（如果构建机器能访问的话）
# RUN npm config set registry https://registry.npmmirror.com

COPY apps/web/package*.json ./
COPY node_modules ./node_modules
COPY apps/web/dist ./dist

EXPOSE 36592

CMD ["node", "dist/index.js"]
